### ISSUE TITLE
ImportError: No module named 'var'

### ISSUE THREAD

**Issue by ddaaggeett** [vmalyi/adb_android#23]
error in the adb_android.py file.  help?

**Comment by vmalyi** [comment]
Could you please attach the error itself, your environment information and version of adb_android you're using?

Thanks!

**Comment by GelaniNijraj** [comment]
Hey, @vmalyi 

I'm facing the same issue. I'm on 64 bit system, running arch linux.
My python version is 3.5.1. Here's the whole error : 
```
Traceback (most recent call last):
  File "get_screen.py", line 1, in <module>
    from adb_android import adb_android
  File "/home/buddha/words/env/lib/python3.5/site-packages/adb_android/adb_android.py", line 4, in <module>
    import var as v
ImportError: No module named 'var'

```

Thanks.

**Comment by vmalyi** [comment]
@GelaniNijraj how did you install this package? Using pip?

**Comment by GelaniNijraj** [comment]
@vmalyi Yes. Using pip on virtualenv.

**Comment by apwork** [comment]
I'm encountering the same issue. Running PYthon 3.5.1 on 64 bit system running Windows 7. Installed via pip. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gunnarsson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\adb_android\adb_android.py", line 4, in <module>

    import var as v
ImportError: No module named 'var'

**Comment by vmalyi** [comment]
Seems like it's related to python 3.5.1

Will take a look into it.

**Comment by GelaniNijraj** [comment]
Thanks.

**Comment by davedaggett** [comment]
my apologies.  i don't recall starting this thread, but history says otherwise.

**Comment by tobyxdd** [comment]
same problem here... python 3.6.0a on Windows 10

**Comment by archieLa** [comment]
Just FYI this is still an issue with Python 3.6.5. The fix for this issue is simple in adb_android.py simple change
```python
import var as v
```
to
```python
from . import var as v
```
