### ISSUE TITLE
from adb_android import adb_android

### ISSUE THREAD

**Issue by riedlblower** [vmalyi/adb_android#24]
Hi,
Overall I found this great altogether and it is much appreciated. For me though to get it to work as per reading the "How to use?" section I had to type 

from adb_android import adb_android

rather than the suggested 

import adb_android

at the top of my file containing my python code.
-M

**Comment by vmalyi** [comment]
Good catch @riedlblower! Thank you! 

Fixed in d8f072930f61e9a894ab2f32dbae13630b9fac05
