### ISSUE TITLE
How to write a SQL update command with root privilege

### ISSUE THREAD

**Issue by henryhoang92** [vmalyi/adb_android#36]
```
adb shell
su -c 'sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update system set value=5000 where name='screen_off_timeout'"
```

But I am getting the following error:

Error: no such column: screen_off_timeout

 how to fix it?

**Comment by vmalyi** [comment]
@henryhoang92  Follow the steps from  https://stackoverflow.com/a/29206366/1254211 and use "adb_android.shell('')" command in order to issue shell commands on step 4 and further.

**Comment by henryhoang92** [comment]
hi @vmalyi . It's not working with  adb_android.shell("su"). 

```
    print adb_android.devices()
    print adb_android.shell("su")
    print adb_android.shell("sqlite3 ./data/settings.db select * from settings")
```

**Comment by henryhoang92** [comment]
Hi @vmalyi  what solution for this issues?
