### ISSUE TITLE
Is it compatible with python3?

### ISSUE THREAD

**Issue by yangxinQA** [vmalyi/adb_android#40]
I  use the package on python 36 and got the mistake .
Is the package compatible with python3?
Traceback (most recent call last):
  File "CPU.py", line 7, in <module>
    from adb_android import adb_android
  File "C:\Users\v_michen\AppData\Local\Programs\Python\Python36\lib\site-packag
es\adb_android\adb_android.py", line 37
    print "IOError: Failed to create a log file"
                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("IOError
: Failed to create a log file")?

**Comment by vmalyi** [comment]
The module should be compatible with Python 3.5.

Could you please try the fix you're proposing and let me know whether it helps?

Thanks!
